services:
  postgres:
    image: postgres:18
    container_name: session-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: session_auth
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: session-auth-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  postgres-data: