services:
  mongodb:
    image: mongo:8
    container_name: tasks-api-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - tasks-api-mongo-data:/data/db

volumes:
  tasks-api-mongo-data: